services:
  - type: web
    name: muzhskoe-zhenskoe-tochnovnotu
    runtime: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --threads 20 app:app
